[package]
name = "mcmmtk_gtk"
version = "0.2.0"
authors = ["Peter Williams <pwil3058@bigpond.net.au> <pwil3058@gmail.com>"]
edition = "2024"

[dependencies]
lazy_static = "0.2.8"

gtk3_ext = { git = "https://github.com/pwil3058/rs_pw_gix" }
path_utilities = { git = "https://github.com/pwil3058/rust_utilities" }

colour_math = { path = "../colour_math" }

[dependencies.epaint]
path = "../epaint"
version = "*"
features = ["targeted_mixtures", "paints_have_ids"]

[dependencies.epaint_gtk]
path = "../epaint_gtk"
version = "*"
features = ["targeted_mixtures", "paints_have_ids"]
