[package]
name = "mcmmtk_gtk"
version = "0.2.0"
authors = ["Peter Williams <pwil3058@bigpond.net.au> <pwil3058@gmail.com>"]
edition = "2024"

[dependencies]
gtk3_ext.workspace = true
path_utilities.workspace = true
recollections.workspace = true

colour_math.workspace = true
epaint = { workspace = true, features = ["targeted_mixtures", "paints_have_ids"] }
epaint_gtk = { workspace = true, features = ["targeted_mixtures", "paints_have_ids"] }
