[package]
name = "colour_math_gtk4"
version = "0.1.0"
authors = ["Peter Williams <pwil3058@bigpond.net.au> <pwil3058@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "*", package = "gtk4", features = ["v4_14"] }
cairo-rs = { version = "*", features = ["png"] }

num-traits = "0.2.14"

num_traits_plus = { git = "https://github.com/pwil3058/rs_num_traits_plus.git" }

gtk_ext = { path = "../gtk_ext" }
gtk_ext_derive = { path = "../gtk_ext_derive" }

colour_math = { path = "../colour_math" }
