// Copyright (c) 2026 Peter Williams <pwil3058@bigpond.net.au> <pwil3058@gmail.com>.

use pw_gtk_ext::sav_state::SAV_NEXT_CONDN;

pub const SAV_EDITING: u64 = SAV_NEXT_CONDN;
pub const SAV_NOT_EDITING: u64 = SAV_NEXT_CONDN << 1;
pub const SAV_ID_READY: u64 = SAV_NEXT_CONDN << 2;
pub const SAV_NAME_READY: u64 = SAV_NEXT_CONDN << 3;
pub const SAV_NOTES_READY: u64 = SAV_NEXT_CONDN << 4;
pub const SAV_HAS_CHANGES: u64 = SAV_NEXT_CONDN << 5;
pub const SAV_ID_CHANGED: u64 = SAV_NEXT_CONDN << 6;
pub const SAV_NAME_CHANGED: u64 = SAV_NEXT_CONDN << 7;
pub const SAV_NOTES_CHANGED: u64 = SAV_NEXT_CONDN << 8;
pub const SAV_RGB_CHANGED: u64 = SAV_NEXT_CONDN << 9;

pub const SAV_FINISH_CHANGED: u64 = SAV_NEXT_CONDN << 10;
pub const SAV_PERMANENCE_CHANGED: u64 = SAV_NEXT_CONDN << 11;
pub const SAV_TRANSPARENCY_CHANGED: u64 = SAV_NEXT_CONDN << 12;
pub const SAV_FLUORESCENCE_CHANGED: u64 = SAV_NEXT_CONDN << 13;
pub const SAV_METALLICNESS_CHANGED: u64 = SAV_NEXT_CONDN << 14;
pub const SAV_OPACITY_CHANGED: u64 = SAV_NEXT_CONDN << 15;
pub const SAV_LIGHTFASTNESS_CHANGED: u64 = SAV_NEXT_CONDN << 16;
pub const SAV_GRANULATION_CHANGED: u64 = SAV_NEXT_CONDN << 17;
pub const SAV_STAINING_CHANGED: u64 = SAV_NEXT_CONDN << 18;

pub const IMAGE_AVAILABLE: u64 = SAV_NEXT_CONDN << 19;
pub const HAS_SAMPLES: u64 = SAV_NEXT_CONDN << 20;

pub const SAV_HAS_COLOUR: u64 = SAV_NEXT_CONDN << 21;
pub const SAV_HAS_TARGET: u64 = SAV_NEXT_CONDN << 22;
pub const SAV_NOT_HAS_TARGET: u64 = SAV_NEXT_CONDN << 23;

pub const SAV_HAS_CURRENT_FILE: u64 = SAV_NEXT_CONDN << 24;
pub const SAV_TOOL_NEEDS_SAVING: u64 = SAV_NEXT_CONDN << 25;
pub const SAV_SESSION_NEEDS_SAVING: u64 = SAV_NEXT_CONDN << 26;
pub const SAV_SESSION_IS_SAVEABLE: u64 = SAV_NEXT_CONDN << 27;

pub const SAV_HAS_NAME: u64 = SAV_NEXT_CONDN << 28;
