[workspace]

resolver = "2"

members = [
    "colour_math",
    "colour_math_cairo",
    "colour_math_derive",
    "colour_math_gtk",
    "colour_math_gui_gtk",
    "epaint",
    "epaint_derive",
    "epaint_gtk",
    "epaint_gtk_gui",
    "wpca_gtk",
    "mcmmtk_gtk",
    "pw_gtk_ext",
    "colour_math_gtk4_gui",
    "colour_math_gtk4",
    "gtk4_ext",
    "gtk4_ext_derive",
    "gtk_ext",
    "gtk_ext_derive",
    "gtk_ext_test_gui",
]
