[package]
name = "colour_math"
version = "0.1.0"
authors = ["Peter Williams <pwil3058@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# cargo.io crates
num-traits.workspace = true
regex.workspace = true
serde.workspace = true
serde_derive.workspace = true

# crates from my github account
num_traits_plus.workspace = true
