[package]
name = "epaint_gtk_gui"
version = "0.2.0"
edition = "2024"

[features]
default = []
paints_have_ids = []
taegeted_mixtures = []
palette_samples = []

[dependencies]

gtk3_ext.workspace = true
recollections.workspace = true

colour_math.workspace = true
colour_math_derive.workspace = true

epaint = { workspace = true, features = ["targeted_mixtures", "paints_have_ids"] }
epaint_gtk = { workspace = true, features = ["targeted_mixtures", "palette_samples", "paints_have_ids"] }

