[package]
name = "gtk_ext"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk = "0.18.2"

cairo-rs = "0.18.2"

pango = "0.18.3"
pangocairo = "0.18.0"
pango-sys = "0.18.0"

sourceview = "0.9.0"

lazy_static = "1.5.0"
mut_static = "5.0.0"
num = "0.4"
num-traits = "0.2.19"
which = "6"

normalised_angles = { git = "https://github.com/pwil3058/rs_normalised_angles.git" }
num_traits_plus = { git = "https://github.com/pwil3058/rs_num_traits_plus.git" }

gtk_ext_derive = { path = "../gtk_ext_derive" }
path_utilities = { path = "../path_utilities" }

[features]
default = ["cairo-rs/png"]
