[package]
name = "colour_math_gtk"
version = "0.2.0"
authors = ["Peter Williams <pwil3058@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits.workspace = true

num_traits_plus.workspace = true

gtk3_ext.workspace = true

colour_math.workspace = true
colour_math_cairo.workspace = true
