[package]
name = "colour_math_gui_gtk"
version = "0.2.0"
authors = ["Peter Williams <pwil3058@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk3_ext.workspace = true
recollections.workspace = true
path_utilities.workspace = true

colour_math = { path = "../colour_math" }
colour_math_gtk = { path = "../colour_math_gtk" }
colour_math_derive = { path = "../colour_math_derive" }
