[package]
name = "epaint_gtk"
version = "0.2.0"
authors = ["Peter Williams <pwil3058@gmail.bigpond.net.au"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
targeted_mixtures = []
palette_samples = []
paints_have_ids = []

[dependencies]
serde.workspace = true
serde_derive.workspace = true

gcd.workspace = true

num_traits_plus.workspace = true

path_utilities.workspace = true
recollections.workspace = true
gtk3_ext.workspace = true

colour_math.workspace = true
colour_math_cairo.workspace = true
colour_math_gtk.workspace = true
epaint = { workspace = true, features = [] }

