[package]
name = "wpca_gtk"
version = "0.1.0"
authors = ["Peter Williams <pwil3058@bigpond.net.au>  <pwil3058@gmail.com>"]
edition = "2024"

[features]
default = []
targeted_mixtures = []
palette_samples = []
paints_have_ids = []

[dependencies]
gtk3_ext.workspace = true
path_utilities.workspace = true
recollections.workspace = true

colour_math.workspace = true
epaint = { workspace = true, features = [] }
epaint_gtk = { workspace = true, features = ["palette_samples"] }

