[package]
name = "epaint"
version = "0.1.0"
edition = "2024"
authors = ["Peter Williams <pwil3058@bigpond.net.au> <pwil3058@bigpond.net.au"]

[features]
default = []
targeted_mixtures = []
paints_have_ids = []

[dependencies]

serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
crypto-hash.workspace = true
gcd.workspace = true
regex.workspace = true

epaint_derive.workspace = true
colour_math.workspace = true
colour_math_derive.workspace = true
